# Chapter 1: Introduction
## 1.1 Introduction
In modern manufacturing industries such as electronics, semiconductor production, printed circuit board manufacturing, wafer inspection and textile production, even small defects can affect product performance, customer satisfaction and production cost. Therefore, defect detection is an important part of industrial quality control. A reliable inspection system helps identify defective products earlier, reduce waste and support stable production.
In many factories, defect inspection is still carried out manually through visual checking by workers. This approach may be acceptable for small-scale production or simple inspection tasks but it becomes difficult for high-volume continuous production. Manual inspection depends heavily on the inspector’s experience and concentration. Over time, fatigue, visual limitations and inconsistent judgement may lead to missed defects or false inspection results. These limitations have encouraged the use of automated defect detection methods.
With the development of artificial intelligence and computer vision, deep learning has been widely applied in industrial defect detection. Methods such as convolutional neural networks, object detection models and anomaly detection algorithms can learn visual patterns from industrial images and support faster and more consistent inspection. Recent studies have also explored incremental learning, few-shot learning and unknown defect detection to help models handle new defect types after deployment.
However, many existing defect detection models are still trained on fixed datasets and deployed as static systems. This is a limitation in real industrial environments where production conditions may change due to lighting variation, camera position, material differences, machine aging or process changes. New or rare defects may also appear during operation but may not be included in the original training data. As a result, a model that performs well during initial testing may become less reliable in actual production.
Another challenge is that many industrial anomaly detection methods are tested using controlled benchmark datasets which may not fully reflect real factory conditions. In actual production lines, defects can be very small, slightly misaligned or difficult to identify without comparison with a normal sample. More than one defect type may also appear on the same product. This makes real industrial defect detection more complex than standard laboratory testing.
In anomaly segmentation, the model usually produces an anomaly score map to show possible defective areas. However, actual inspection requires a clear decision on which area is defective and which area is normal. A common method is to use a fixed threshold to separate abnormal regions from normal regions. This method is simple, but it may not remain reliable when lighting, camera angle, material surface or defect patterns change. Therefore, a more adaptive method is needed during testing.
This research follows a test-time learning workflow where each new test image is compared with stored normal feature patterns. The system measures how different the new image is from the normal references and uses this difference to decide whether the image is normal or abnormal. When a new sample appears to be normal, its features can be added into the memory bank to update the normal representation. This allows the system to gradually adapt to new production conditions without full retraining.
Practical implementation is also important. Many deep learning methods require programming skills and technical knowledge, which may limit their use by industrial users. A low-code platform can reduce this barrier by allowing users to build, adjust and operate the defect detection workflow with less manual coding. This makes the system more accessible to engineers, quality control staff and users who may not specialize in artificial intelligence.
Therefore, this research focuses on the development of an online test-time learning method for industrial defect detection using a low-code platform. The aim is to support adaptive defect detection during operation while keeping the system practical and user-friendly for industrial use.

## 1.2 Research Problem
Although many studies have improved the accuracy of industrial defect detection, several practical issues remain.
First, many existing defect detection models are trained as static systems. Once deployed, the model normally does not update unless retraining or fine-tuning is carried out. This can become a limitation in real production environments where lighting conditions, material appearance, camera settings or product variations may change over time. New or rare defect patterns may also appear during operation but they may not be available in the original training data.
Second, incremental learning methods have been proposed to reduce the need for full retraining. However, many of these methods still depend on offline or staged updates where new data must be collected and used in a separate training process. This does not fully reflect a real online inspection setting where test samples arrive continuously and the system may need to respond immediately.
Third, many existing approaches focus mainly on improving model accuracy or reducing catastrophic forgetting. Less attention is given to practical implementation such as how the system can be arranged into a clear workflow, tested in a notebook environment and later transferred into a low-code or user-friendly platform. In industrial environments, a defect detection system should not only be accurate but also simple to operate, flexible to adjust and easier to deploy.
Therefore, there is still a gap between current research methods and practical industrial needs. This study addresses the gap by developing an online test-time learning workflow for industrial anomaly detection. The proposed method uses a frozen YOLO-based feature extractor, an online adapter and a normal memory bank to detect anomalies and update the normal representation using accepted normal samples during testing.

## 1.3 Research Questions
This study aims to answer the following research questions:
RQ1: How can a frozen YOLO-based feature extractor and normal memory bank be used for industrial anomaly detection?
RQ2: How can online test-time learning update the system during inference without retraining the full model?
RQ3: How can normal-like test samples be selected safely to update the online adapter and memory bank?
RQ4: How effective is the proposed online test-time learning method compared with the baseline setting without adaptation?
RQ5: How can the proposed workflow be structured in a modular notebook and later prepared for low-code implementation?

## 1.4 Research Objectives
To address the research questions, the objectives of this study are:
RO1: To design an industrial anomaly detection workflow using a frozen YOLO26 feature extractor, online adapter and normal memory bank.
RO2: To develop an online test-time learning mechanism that updates only the lightweight adapter and memory bank without retraining the full YOLO model.
RO3: To apply a normal sample acceptance rule so that only reliable test samples are used for online adaptation.
RO4: To evaluate the proposed method by comparing performance before and after online test-time adaptation using AUROC, precision, recall, F1-score, confusion matrix, score distribution and error cases.
RO5: To structure the implementation in a modular and user-friendly workflow that can support future low-code platform development.

## 1.5 Scope of Study
This research focuses on image-based industrial anomaly detection using the MVTec AD dataset. The dataset contains 15 industrial categories, including objects and textures such as bottle, cable, capsule, carpet, grid, hazelnut, leather, metal nut, pill, screw, tile, toothbrush, transistor, wood and zipper.
The study follows an unsupervised anomaly detection setting. Only normal images are used during preparation to build the normal memory bank and calibrate the anomaly threshold. Defective images are not used for training or threshold calibration. They are used only during testing and evaluation.
The proposed method uses a frozen YOLO26 classification model as the feature extractor. The full YOLO model is not retrained. Instead, image embeddings are extracted before the final classification layer. These embeddings are passed through a lightweight online adapter and compared with normal reference features stored in the memory bank. During online testing, each test image is processed one by one. If a test sample is considered normal, the adapter is updated using consistency and anchor losses and the accepted feature is added to the memory bank.
The experiment is implemented in a Kaggle notebook environment with GPU acceleration. The current work focuses on algorithm development, experimental validation and workflow design. It does not include hardware development, camera integration, real-time factory deployment or a full production-level low-code software system. Instead, the modular notebook workflow is designed as a foundation for future low-code implementation.

